name: CI

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      camunda:
        image: camunda/camunda-bpm-platform:7.17.0
        ports:
        - 8080:8080

    steps:
    - uses: actions/checkout@v4
    - name: Read .nvmrc
      run: echo "name=node_version::$(cat .nvmrc)" >> $GITHUB_OUTPUT
      id: nvm
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '${{ steps.nvm.outputs.node_version }}'
    - run: npm ci
    - run: npm run lint
    - run: npm run test
