name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      camunda:
        image: camunda/camunda-bpm-platform:latest
        ports:
        - 8080:8080

    steps:
    - uses: actions/checkout@v2
    - name: Read .nvmrc
      run: echo ::set-output name=node_version::$(cat .nvmrc)
      id: nvm
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '${{ steps.nvm.outputs.node_version }}'
    - run: npm run lint
    - run: npm run test
